###
PUT http://localhost:4000/api/labs/63210bf813e6f82bbd5bab98
Content-Type: application/json

{
  "labName": "New Lab",
  "users": [
    {
      "id": 1, 
      "name": "Kyle", 
      "role": "basic"
    }
  ]
}